config/routes.rb
Link::Application.routes.draw do

  resources :users do
    resources :contacts
  end

  resources :identities
  

  root :to => 'home#index'
  
  match "/auth/:provider/callback", :to =>  "sessions#create"
  match "/auth/failure", :to => "sessions#failure"
  match "/signout", :to => "sessions#destroy", :as => "signout"
  
  match "/import", :to => "contacts#import_contacts", :as => "import_contacts"
  
  get "/:provider/contacts" => "contacts#import_contacts"
  get "/:provider/contacts/failure" => "users#failure"
  
  
  match "/contacts", :to => "users#contacts", :as => "contacts_list"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :name, :source, :user_id
  belongs_to :user
  validates_uniqueness_of :email
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  attr_accessible :email, :name, :password_digest
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/user.rb
class User < ActiveRecord::Base
  
  extend FriendlyId
  friendly_id :name, :use => :history
  
  attr_accessible :email, :name, :provider, :uid
  
  has_many :contacts
  
  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  protected

  def current_user
    @current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end
  
  private
 
  def require_login
    unless signed_in?
      respond_to do |format|
        format.html { redirect_to root_url }
      end
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  layout "profile"
  before_filter :require_login
  
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts.paginate(:page => params[:page], :per_page => 30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end  
  
  def import_contacts
    @contacts = request.env['omnicontacts.contacts']
    
    @contacts.each do |contact|
    current_user.contacts.create(:name => contact[:name], :email => contact[:email])
    end
    
    respond_to do |format|
      format.html { redirect_to user_contacts_url(current_user) }
      format.json { head :no_content }
    end
    
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to user_path(current_user) if current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login
  
  def new
    redirect_to root_url if current_user
  end
  
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to user_path(current_user)
  end
  
  def destroy
    @current_user = session[:user_id] = nil
    redirect_to root_url, :notice => 'Signed out!'
  end
  
  def failure
    flash[:error] = "Authentication failed, please try again." 
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "profile"
  before_filter :require_login
  
  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/index.html.erb
<h3><strong>Listing <%=link_to "#{current_user.name}'s", current_user%> contacts</strong></h3>
<strong><%=link_to "Back to profile", current_user%></strong>

<hr>

<%if @contacts.blank?%>
<p>
	No contacts found!. <br> Please <%=link_to "Import #{current_user.provider} contacts", "/contacts/gmail" %> first.
</p>	
<%else%>
<div class="row">
	<div class="span12">
		<%= page_entries_info @contacts %>
		<%= will_paginate @contacts, :class=>"pull-right"%>
	</div>	
</div>	
<table class="table table-condensed">
	<tr>
		<th>Name</th>
		<th>Email</th>
	</tr>
	<% @contacts.each do |contact| %>
	<tr>
		<td><%= contact.name %></td>
		<td><%= mail_to contact.email %></td>
	</tr>
	<% end %>
</table>
<%= will_paginate @contacts, :class=>"pagination pagination-right"%>
<%end%>

app/views/home/index.html.erb
<center>
	<a href="/auth/google" class="btn btn-primary btn-large">
		<i class="icon-google icon-white"></i><b>Sign up using google</b>
	</a>
</center>		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Link</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="span6 offset3 flash_container">
				<div class="flash_messages"><center><%= render :partial => "shared/flash_messages" %></center></div>
			</div>
		</div>
	
		<div class="row">
			<div class="span12">
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Link</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a href="/" class="brand">Link</a>
				<div class="nav-collapse collapse">
					<ul class="nav pull-right">	        
						<li><%= link_to "Welcome! #{current_user.name}", user_path(current_user)%></li>
						<li><%= link_to "Sign out", :signout %></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	
	<div class="container">
		<div class="row">
			<div class="span6 offset3 flash_container">
				<div class="flash_messages"><center><%= render :partial => "shared/flash_messages" %></center></div>
			</div>
		</div>
		
		<%= yield %>
	</div>
</body>
</html>

app/views/shared/_flash_messages.html.erb
<% unless flash[:error].blank? %>
<div class="alert alert-error">
	<a class="close" data-dismiss="alert">×</a>
	<%=flash[:error]%>
</div>
<% end %>

<% unless flash[:notice].blank? %>
<div class="alert alert-success">
	<a class="close" data-dismiss="alert">×</a>
	<%=flash[:notice]%>
</div>
<% end %>

<% unless flash[:info].blank? %>
<div class="alert alert-info">
	<a class="close" data-dismiss="alert">×</a>
	<%=flash[:info]%>
</div>
<% end %>

<% unless flash[:alert].blank? %>
<div class="alert alert-block">
	<a class="close" data-dismiss="alert">×</a>
	<strong><%=flash[:alert]%></strong>
</div>
<% end %>

app/views/users/failure.html.erb
Authentication failed

app/views/users/show.html.erb
<div class="row">
	<div class="span12">
		
		<h3>
			<%=link_to "Import #{@user.provider} contacts", "/contacts/gmail" if @user == current_user%>
		</h3>	
		
		<p>
			<b>Name:</b>
			<%= @user.name %>
		</p>

		<p>
			<b>Email:</b>
			<%= @user.email %>
		</p>

		<p>
			<b>Provider:</b>
			<%= @user.provider %>
		</p>


		
		<p>
			<%=link_to "Show #{@user.provider} contacts", user_contacts_path(@user) if @user == current_user%>
		</p>
			
	</div>
	
</div>	